[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "klipper_led_effect"
readme = "README.md"
license = { text = "GPL3" }
version = "0.0.10"

[tool.setuptools]
packages = [ "klipper_led_effect" ]
